# Generated by Django 2.1.3 on 2018-12-05 00:50

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'item', app_label='sample')


class Migration(migrations.Migration):
    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
