# Generated by Django 2.1.3 on 2019-01-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('detail', models.TextField(blank=True, max_length=1000, null=True, verbose_name='詳細')),
                ('status', models.IntegerField(default=0, verbose_name='ステータス')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録時間')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='登録時間')),
            ],
            options={
                'verbose_name': 'ToDoタスク',
                'verbose_name_plural': 'ToDoタスク',
            },
        ),
    ]
