# Generated by Django 2.1.3 on 2019-01-04 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('status', models.IntegerField(choices=[(0, '新規'), (1, '対応中'), (2, '完了')], default=0, verbose_name='ステータス')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済み')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='登録時間')),
            ],
            options={
                'verbose_name': 'ToDoタスク',
                'verbose_name_plural': 'ToDoタスク',
            },
        ),
    ]
