# Generated by Django 2.1.3 on 2019-01-11 02:21
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'tasks', app_label='todo')


class Migration(migrations.Migration):
    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
