# Generated by Django 2.1.3 on 2019-01-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190104_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, '未着手'), (1, '対応中'), (2, '完了')], default=0, verbose_name='ステータス'),
        ),
    ]
